import './index.css';

export const cssVariables = {
    primaryColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-color'),
    primaryContainerColor: getComputedStyle(document.documentElement).getPropertyValue('--primary-container-color'),
    secondaryColor: getComputedStyle(document.documentElement).getPropertyValue('--secondary-color'),
    secondaryContainerColor: getComputedStyle(document.documentElement).getPropertyValue('--secondary-container-color'),
    surfaceColor: getComputedStyle(document.documentElement).getPropertyValue('--surface-color'),
    surfaceVariantColor: getComputedStyle(document.documentElement).getPropertyValue('--surface-variant-color'),
    backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--background-color'),
    errorColor: getComputedStyle(document.documentElement).getPropertyValue('--error-color'),
    errorContainerColor: getComputedStyle(document.documentElement).getPropertyValue('--error-container-color'),
    onPrimaryColor: getComputedStyle(document.documentElement).getPropertyValue('--on-primary-color'),
    onPrimaryContainerColor: getComputedStyle(document.documentElement).getPropertyValue('--on-primary-container-color'),
    onSecondaryColor: getComputedStyle(document.documentElement).getPropertyValue('--on-secondary-color'),
    onSecondaryContainerColor: getComputedStyle(document.documentElement).getPropertyValue('--on-secondary-container-color'),
    onSurfaceColor: getComputedStyle(document.documentElement).getPropertyValue('--on-surface-color'),
    onSurfaceVariantColor: getComputedStyle(document.documentElement).getPropertyValue('--on-surface-variant-color'),
    onErrorColor: getComputedStyle(document.documentElement).getPropertyValue('--on-error-color'),
    onErrorContainerColor: getComputedStyle(document.documentElement).getPropertyValue('--on-error-container-color'),
    onBackground: getComputedStyle(document.documentElement).getPropertyValue('--on-background'),
    outlineColor: getComputedStyle(document.documentElement).getPropertyValue('--outline-color'),
    outlineVariantColor: getComputedStyle(document.documentElement).getPropertyValue('--outline-variant-color'),
    shadowColor: getComputedStyle(document.documentElement).getPropertyValue('--shadow-color' ),
    surfaceTintColor: getComputedStyle(document.documentElement).getPropertyValue('--surface-tint-color'),
    inverseSurfaceColor: getComputedStyle(document.documentElement).getPropertyValue('--inverse-surface-color'),
    inverseOnSurfaceColor: getComputedStyle(document.documentElement).getPropertyValue('--inverse-on-surface-color'),
    inversePrimaryColor: getComputedStyle(document.documentElement).getPropertyValue('--inverse-primary-color'),
    fontSizeDisplayLarge: getComputedStyle(document.documentElement).getPropertyValue('--font-size-display-large'),
    fontSizeDisplayMedium: getComputedStyle(document.documentElement).getPropertyValue('--font-size-display-medium'),
    fontSizeDisplaySmall: getComputedStyle(document.documentElement).getPropertyValue('--font-size-display-small'),
    fontSizeHeadlineLarge: getComputedStyle(document.documentElement).getPropertyValue('--font-size-headline-large'),
    fontSizeHeadlineMedium: getComputedStyle(document.documentElement).getPropertyValue('--font-size-headline-medium'),
    fontSizeHeadlineSmall: getComputedStyle(document.documentElement).getPropertyValue('--font-size-headline-small'),
    fontSizeTitleLarge: getComputedStyle(document.documentElement).getPropertyValue('--font-size-title-large'),
    fontSizeTitleMedium: getComputedStyle(document.documentElement).getPropertyValue('--font-size-title-medium'),
    fontSizeTitleSmall: getComputedStyle(document.documentElement).getPropertyValue('--font-size-title-small'),
    fontSizeLabelLarge: getComputedStyle(document.documentElement).getPropertyValue('--font-size-label-large'),
    fontSizeLabelMedium: getComputedStyle(document.documentElement).getPropertyValue('--font-size-label-medium'),
    fontSizeLabelSmall: getComputedStyle(document.documentElement).getPropertyValue('--font-size-label-small'),
    fontSizeBodyLarge: getComputedStyle(document.documentElement).getPropertyValue('--font-size-body-large'),
    fontSizeBodyMedium: getComputedStyle(document.documentElement).getPropertyValue('--font-size-body-medium'),
    fontSizeBodySmall: getComputedStyle(document.documentElement).getPropertyValue('--font-size-body-small'),
    lineHeightDisplayLarge: getComputedStyle(document.documentElement).getPropertyValue('--line-height-display-large'),
    lineHeightDisplayMedium: getComputedStyle(document.documentElement).getPropertyValue('--line-height-display-medium'),
    lineHeightDisplaySmall: getComputedStyle(document.documentElement).getPropertyValue('--line-height-display-small'),
    lineHeightHeadlineLarge: getComputedStyle(document.documentElement).getPropertyValue('--line-height-headline-large'),
    lineHeightHeadlineMedium: getComputedStyle(document.documentElement).getPropertyValue('--line-height-headline-medium'),
    lineHeightHeadlineSmall: getComputedStyle(document.documentElement).getPropertyValue('--line-height-headline-small'),
    lineHeightTitleLarge: getComputedStyle(document.documentElement).getPropertyValue('--line-height-title-large'),
    lineHeightTitleMedium: getComputedStyle(document.documentElement).getPropertyValue('--line-height-title-medium'),
    lineHeightTitleSmall: getComputedStyle(document.documentElement).getPropertyValue('--line-height-title-small'),
    lineHeightLabelLarge: getComputedStyle(document.documentElement).getPropertyValue('--line-height-label-large'),
    lineHeightLabelMedium: getComputedStyle(document.documentElement).getPropertyValue('--line-height-label-medium'),
    lineHeightLabelSmall: getComputedStyle(document.documentElement).getPropertyValue('--line-height-label-small'),
    lineHeightBodyLarge: getComputedStyle(document.documentElement).getPropertyValue('--line-height-body-large'),
    lineHeightBodyMedium: getComputedStyle(document.documentElement).getPropertyValue('--line-height-body-medium'),
    lineHeightBodySmall: getComputedStyle(document.documentElement).getPropertyValue('--line-height-body-small'),
};

export * from "./components";